---
title: "Collocation"
author: 
  - name:
      given: "Gede Primahadi Wijaya"
      family: "Rajeg"
    url: https://www.ling-phil.ox.ac.uk/people/gede-rajeg
    orcid: 0000-0002-2047-8621
    affiliation:
      - '<a href="https://www.ling-phil.ox.ac.uk/people/gede-rajeg" target="_blank" style="color:DodgerBlue;">University of Oxford</a> / <a href="https://www.cirhss.org/" target="_blank" style="color:DodgerBlue;">CIRHSS</a> & <a href="https://github.com/complexico" target="_blank" style="color:DodgerBlue;">CompLexico</a>, Udayana University'
format: 
  revealjs:
    slide-number: true
    preview-links: auto
    css: styles.css
date: 2024-07-22
date-modified: now
editor: visual
bibliography: references.bib
csl: "https://raw.githubusercontent.com/citation-style-language/styles/master/unified-style-sheet-for-linguistics.csl"
---

## Roadmap

::: incremental
1.  Collocation: A brief history & basic notion

2.  Two methodological perspectives on “collocation”

3.  Why is collocation useful?

4.  Practice
:::

## Collocation: A brief history & basic notion {.scrollable}

::: incremental
-   First used by J. R. Firth (1957):

    > “I propose to bring forward as a technical term, meaning by *collocation*, and apply the test of *collocability*.” [Firth 1957: 194, cited from @xiao2015, 107]

-   “Collocations of a given word are statements of the habitual or customary places of that word” [@firth1962, 12]

    -   NOT just a “mere juxtaposition”, but “an order of *mutual expectancy*” [@firth1962, 12]

-   Aspect of the “[Neo-Firthian Corpus Linguistics]{style="color:crimson"}” [@mcenery2012, Ch. 6]

    -   leading figure: John Sinclair

    -   [Firth's idea meets corpus linguistics]{style="color:crimson"}

    -   Two central approaches: **collocation** & **discourse**

    -   meaning by collocation:

        -   an important aspect of word meaning does not exist in isolation but subsists in the features of association that word participates in with other words and/or structures it frequently co-occurs [@mcenery2012, 123]

-   broad definition:

    > “co-occurrence patterns observed in corpus data” [@mcenery2012, 123]

    -   but how is this “co-occurrence” identified?

    -   there are two broad methodological/operational perspectives
:::

## Roadmap

::: nonincremental
~~1. Collocation: A brief history & basic notion~~

2.  Two methodological perspectives on “collocation”

3.  Why is collocation useful?

4.  Practice
:::

## Two methodological perspectives on “collocation” {.scrollable}

::: columns
::: {.column width="50%"}
“collocation via concordance”

-   manual scanning of concordance lines

-   linguist's intuition + linguistic skill

-   e.g., Sinclair's classic study on *naked eye*.

-   my experience:

    -   focus on syntactically relevant words of the node

    -   I use it to study metaphoric construction and conceptual metaphor for emotion
:::

::: {.column width="50%"}
:::
:::

## Two methodological perspectives on “collocation” {.scrollable}

::: columns
::: {.column .suppressedtextcolour width="50%"}
“collocation via concordance”

-   manual scanning of concordance lines

-   linguist's intuition + linguistic skill

-   e.g., Sinclair's classic study on *naked eye*.

-   my experience:

    -   focus on syntactically relevant words of the node

    -   I use it to study metaphoric construction and conceptual metaphor for emotion
:::

::: {.column width="50%"}
“collocation via significance”

-   statistical test on the co-occurrence frequency

-   commonly available in modern corpus tools

-   mainly ignore syntactic relation

    -   relying on linear span of words around the node [cf. @hunston2002, 69]

    -   but cf. SkE's *Word Sketch*

-   there is also syntactically-oriented collocation [cf. @stefanowitsch2009]

    -   e.g., *Collostructional Analysis* [@stefanowitsch2013]

        -   manual inspection is still used

    -   or SkE's Word Sketch

        -   in a click of a button
:::
:::

::: r-stack
[See McEnery and Hardie [-@mcenery2012, 123*ff* for details]]{style="color:Thistle"}
:::

## Roadmap

::: nonincremental
~~1. Collocation: A brief history & basic notion~~

~~2. Two methodological perspectives on “collocation”~~

3.  Why is collocation useful?

4.  Practice
:::

## Why is collocation useful? {.scrollable}

::: incremental
-   to detect [different senses of a word]{style="color:#DE3163"} based on its collocate types [@hunston2002]

    -   [For instance, the different sense of *deep*]{style="color:#34495E"} (<https://ske.li/16i>)

-   to reveal [phraseology]{style="color:#DE3163"} of a given node word [@hunston2002, 77-78]

    -   [We could use an n-gram tool, another kind of co-occurrence concept]{style="color:#34495E"} [@mcenery2012, 123]

    -   [For example, the phraseology for the word *shoulder*]{style="color:#34495E"} (<https://ske.li/16l>)

-   to unpack [variation in the usage patterns of near-synonyms]{style="color:#DE3163"} [@xiao2015]

    -   [For instance, distinct co-occurrence patterns of *happiness* and *joy*]{style="color:#34495E"} (<https://ske.li/16j>) [cf. @stefanowitsch2004]

-   to obtain the [profile of semantic field]{style="color:#DE3163"} of a word [@hunston2002]

    -   Example 1: the semantic field of the EXPERIENCER ([fig](https://github.com/complexico/anger-mad-coca/blob/main/figs/08-fig3-8-Experiencer-collocates.png)) noun-collocates of *angry* vs. *mad* [@suari2024] (cf. the repository for data and code [here](https://github.com/complexico/anger-mad-coca/tree/main))

        ![The semantic field of EXPERIENCER collocates for *angry* and *mad* in COCA in the pattern \[*angry*/*mad* NOUN\].](img/08-fig3-8-Experiencer-collocates.png)

        -   the semantic categorisation for these collocates refers to the cross-linguistic semantic catalogue called the [*Concepticon*](https://concepticon.clld.org) [@list2016]

    -   Example 2: the semantic field profile of *bribe* and *bribery* [see @hunston2002, 78]
:::

## Roadmap

::: nonincremental
~~1. Collocation: A brief history & basic notion~~

~~2. Two methodological perspectives on “collocation”~~

~~3. Why is collocation useful?~~

4.  Practice
:::

# End of `Collocation`

- source files for all materials:

    - <https://github.com/complexico/dipscorling2024>

- pdf version as a handout [here](https://github.com/complexico/dipscorling2024/blob/main/03-collocation.pdf)

- How to cite these materials:

    > Rajeg, Gede Primahadi Wijaya. 2024. Materials for the *Diponegoro Summer Course in Corpus Linguistics* (*DipSCORLING 2024*) (22 - 27 July 2024). R Quarto. Zenodo. [https://doi.org/10.5281/zenodo.12793922](https://doi.org/10.5281/zenodo.12793922). (22 July, 2024).

## References
